services:
  nginx:
    image: nginx:1.20.0-alpine
    container_name: nginx
    hostname: sirnoob.duckdns.org
    volumes:
      - ./sirnoob.duckdns.org:/var/www/sirnoob.duckdns.org:ro
      - ./nginx/sirnoob.duckdns.org.conf:/etc/nginx/conf.d/sirnoob.duckdns.org.conf:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:8080"
