name: CI

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker Meta
        uses: crazy-max/ghaction-docker-meta@v2
        id: meta
        with:
          images: ${{ secrets.DK_USERNAME }}/website
          tags: |
            type=ref,event=tag
            type=semver,pattern={{raw}}

      - name: QEMU
        uses: docker/setup-qemu-action@v1

      - name: Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DK_USERNAME }}
          password: ${{ secrets.DK_PASSWORD }}

      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: amd64

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
