name: CI

on:
  push:
    branches: [ nginx ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set Env Variables
        run: |
          IMAGE="${{ secrets.DK_USERNAME }}/web-site"
          VERSION="$(git describe --tags --abbrev=0)"
          echo "IMAGE=${IMAGE}" >> GITHUB_ENV
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
      
      - name: QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DK_USERNAME }}
          password: ${{ secrets.DK_PASSWORD }}
      
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tag: | 
            ${{ env.IMAGE }}:latest
            ${{ env.IMAGE }}:${{ env.VERSION }}
          platforms: amd64
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
